apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: observatorium-api
spec:
  host: observatorium.hub
  port:
    targetPort: public
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: observability-observatorium-observatorium-api
  wildcardPolicy: None